version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 5ecr37
#    expose: # Expose is never needed, it only serves for documentation purpose
#      - 3306
    volumes:
  #    - /tmp/mysql:/var/lib/mysql
  # https://github.com/docker-library/docs/tree/master/mysql#initializing-a-fresh-instance
# The following enables use to place ourdatadump.sql, otherdump.sql inside ./initData
      - $PWD/initData:/docker-entrypoint-initdb.d:ro
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
      - db:mysql
    ports: # ports actually map them to the host, while expose does nothing
      - 8080:80
    environment: # I haven't tried it without the botton two, but they may be obmitted I assume
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 5ecr37
# The following code is not done
# but serves an illustrative purpose
#  proxy: #proxy can be used to do basicauth or ip filtering
#    image: nginx:alpine
#    links:
#      - phpmyadmin
#      - phpmyadmin:phpmyadmin
#    ports:
#      - 80:80
#    volumes:
#      - $PWD/nginx.conf:/etc/nginx/nginx.conf:ro
