version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 5ecr37
#    expose:
#      - 3306
    volumes:
  #    - /tmp/mysql:/var/lib/mysql
  # https://github.com/docker-library/docs/tree/master/mysql#initializing-a-fresh-instance
      - $PWD/initData:/docker-entrypoint-initdb.d:ro
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:mysql
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 5ecr37
