current-context: federal-context
apiVersion: v1
clusters:
- cluster:
    api-version: v1
    insecure-skip-tls-verify: true
    server: https://kubernetes.default
  name: main
contexts:
- context:
    cluster: main
    namespace: default
    user: myserviceaccount
  name: federal-context
kind: Config
preferences:
  colors: true
users:
- name: myserviceaccount
  user:
    token: REDACTED
