version: '2'
services:
  bro:
    image: svlentink/iot-bro
    volumes:
      - ~/cloud9/logbook/henk/wlan0.pcapng:/input:ro # your input file
      - webroot:/output # used for the webview
  cdn:
    image: nginx:alpine
    volumes:
      - webroot:/usr/share/nginx/html:ro #default location of nginx container
    ports:
      - 8080:80
volumes:
  webroot: # cross mounting between containers
