version: '3'
services:
  dropbox:
    image: oddlid/dropbox #janeczku/dropbox
    user: root
    entrypoint: /entry
    volumes:
      - ~/Dropbox:/root/Dropbox
      - $PWD/docker-entrypoint.sh:/entry:ro

