version: '3'
services:
  cdn:
    image: svlentink/mywebsite
    volumes:
      - $PWD/homework.conf:/etc/nginx/conf.d/homework.conf:ro
      - ~/.sekretoj/sslcerts:/sslcerts:ro
      - /tmp/.well-known:/tmp/.well-known:ro # hub.docker.com/r/svlentink/letsencrypt
      - ~/.sekretoj/wordpress:/authdir:ro
      - ~/Dropbox/cdndata/pdf:/var/www/cdn.lent.ink/pdf:ro
      - ~/Dropbox/cdndata/tar:/var/www/cdn.lent.ink/tar:ro
      - ~/Dropbox/cdndata/img:/var/www/cdn.lent.ink/img:ro
      - $PWD/generated:/var/www/cdn.lent.ink/generated:ro
      - /tmp/filesharing:/filesharing:ro
      - ~/wordpress-backup/nginx.conf:/etc/nginx/conf.d/wordpress.conf:ro
      - ~/wordpress-backup:/var/php
      - ~/lois:/lois:ro
      - ~/lois/nginx.conf:/etc/nginx/conf.d/lois.conf:ro
    ports:
      - "80:80"
      - "443:443"
    links:
      - ide
      - ide:ide
      - php
      - php:php
  ide:
    build:
      context: .
      dockerfile: ide.Dockerfile
    volumes:
      - ~/Dropbox/webIDE:/workspace
    env_file:
      - ~/.sekretoj/webIDE/.webIDE.env
    command: ["-a", "$MYUSER:$PASSWD"] # .env should contain these variables

# TODO create cdn.lent.ink/js compiler
  download-cryptojs:
    build:
      context: .
      dockerfile: bower.Dockerfile
    volumes:
      - $PWD/generated:/generated
#  compile-resume:
#    image: svlentink/texlive-full
#    volumes:
#      - $PWD:/data
#    command: texi2pdf --tidy --shell-escape --output=/data/resume.pdf /data/resume.tex

  php:
    image: svlentink/wordpress-sqlite:fpm
    volumes:
      - ~/wordpress-backup:/var/php
    #command: ["php-fpm","-d","cgi.fix_pathinfo=0","--allow-to-run-as-root","--nodaemonize"]
    entrypoint: ["php-fpm"]

  ssl:
    image: svlentink/letsencrypt
    volumes:
      - /tmp:/challenge
      - ~/sslcerts:/pemfiles
    environment:
      EMAIL: ssl@lent.ink
    command: lent.ink blog.lent.ink cdn.lent.ink dev.lent.ink lisanne.lent.ink loiszoektwerk.nl loiszoektwerk.be juflisanne.nl

  wordpress:
    image: svlentink/wordpress-sqlite
    volumes:
      - ~/wordpress-backup/lisanne.lent.ink:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["apache2-foreground"]

