# Ubuntu -> Node.js -> Bower -> Your_Magic (e.g. Polymer)
FROM node:latest
MAINTAINER svlentink <svlentink@gmail.com>
LABEL Description="Just bower, for chaining (which depends on Node.js and NPM)"

ENV DEBIAN_FRONTEND noninteractive

RUN npm install -g bower
