version: '3'
services:
  ide:
    image: svlentink/code-server #codercom/code-server
    command: ["--auth", "none"]
    user: root # avoids issues with mounted volumes
    volumes:
    - /mnt/stateful:/home/coder/stateful
    - /mnt/stateful/.gitconfig:/root/.gitconfig
    - $PWD/login-to-host.sh:/home/coder/login-to-host.sh:ro
    - $PWD/sshkey:/sshkey:ro
#    - /etc/timezone:/etc/timezone:ro
#    - $PWD/kubeconfig.yml:/home/coder/.kube/config.yml

  firewall:
    image: svlentink/ipfilter
    links:
    - ide
    - ide:dontchangethisalias
    volumes:
    - $PWD/passdir:/passdir:ro #used to get the .htpasswd
    ports:
    - 443:4321 # edit only the first part to specify the port for the host
    environment:
      APP_PORT: 8080 # The port the app wants exposed
  # filter based on IP
#      ALLOWED_IPS: 8.8.8.8/32 85.144.250.1/22
    env_file: # we need the CommonName since VS code want to set a service worker
    - .env
