FROM gettyimages/spark:2.0.2-hadoop-2.7

# https://developer.couchbase.com/documentation/server/4.5/connectors/spark-2.0/download-links.html
# https://spark-packages.org/package/couchbase/couchbase-spark-connector
RUN bin/spark-shell --packages com.couchbase.client:spark-connector_2.11:2.0.0

