version: '3'
services:
  dns:
    image: svlentink/dnssec
    environment:
      IPV4MASTER: 10.20.30.40
      IPV4SLAVE: 10.20.30.40
      SERVERTYPE: master
    volumes:
      - $PWD/myzones:/zonefiles
      - ~/dnskeys:/keys
    ports:
      - 53:53/tcp
      - 53:53/udp
