version: '3'
services:
  browser:
    build: .
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11
#    volumes:
#      - /etc/timezone:/etc/timezone:ro
  novnc:  
    image: psharkey/novnc
    environment:
      - DISPLAY_WIDTH=1200
      - DISPLAY_HEIGHT=900
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:

#docker run --rm
#--volumes-from storage
#--env SOCKS_SERVER="socks://172.17.0.1:5080"
#--env SOCKS_VERSION=5
#--env DISPLAY="${DISPLAY}"
#--volume /tmp/.X11-unix:/tmp/.X11-unix
#--env PULSE_SERVER="unix:/tmp/pulse-unix"
#--volume /run/user/"${UID}"/pulse/native:/tmp/pulse-unix
#"${dri_devices[@]}"
#devurandom/firefox "$@"
