version: '2'
services:
  csr:
    image:svlentink/certbot-csr
    volumes:
#      - $PWD/openssl-req.conf:/openssl.conf:ro # using this prevents the generation
      - /tmp:/outputdir
    environment:
      ORGANIZATION: Os3.nl SSN lab assignment
      COUNTRY_CODE: NL
      PROVINCE: Flevoland
      CITY: Lelystad
    command: sanderlentink.nl lent.ink curly.ninja #fqdn
