version: '3'
services:
  browser:
    image: svlentink/dell-idrac
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11
#    volumes:
#      - /etc/timezone:/etc/timezone:ro
  novnc:  
    image: psharkey/novnc
    environment:
      - DISPLAY_WIDTH=1200
      - DISPLAY_HEIGHT=900
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:

