version: '2'
services:
  firewall:
    image: svlentink/ipfilter
    links:
      - app
      - app:app #creating a reference that we'll use
    ports:
      - 163:4321 # edit only the first part to specify the port for the host
    environment:
#      ALLOWED_IPS: 83.96.180.101/32 8.8.8.8/32
      APP_PORT: 8181 # The port the app wants exposed
  app:
    image: sapk/cloud9
    volumes:
      - ~/cloud9:/workspace
    command: ["--auth", "$MYUSER:$PASSWD"] # .env should contain these variables
