version: '2'
services:
  ide:
    image: kdelfour/cloud9-docker
#    mem_limit: 128m
    volumes:
      - $PWD:/workspace/
  proxy:
    image: nginx:alpine # svlentink/naxsi
    volumes:
      - $PWD/htpasswd:/htpasswd:ro # login
      - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - $PWD/public:/public:ro # content
    links:
      - ide
      - ide:ide
    ports:
      - "80:8001"
      - "163:163"
# 163 looks like IdE
