# GPLv3

tmpDir=/tmp/texTmp # location in docker
mountedVolume=/data # the user uses docker run -v <LaTeXDir_on_Host_which_is_probably_just_a_dot>:/data
outputFile=$mountedVolume/.autogenerated.tex # please keep this in reach, outside docker, for easy debugging

#located on host, accessable through by providing volume
docsDir=$mountedVolume/content/docs
