version: '3'
services:
  cdn:
    image: nginx:alpine
    volumes:
      - shared-challenge-volume:/usr/share/nginx/html/.well-known/acme-challenge:ro
    ports:
      - "80:80"
  ssl:
    image: svlentink/letsencrypt
    volumes:
      - shared-challenge-volume:/challenge/.well-known/acme-challenge
      - $PWD/certificatefiles:/pemfiles
# Example options:
      # auth-hook; https://certbot.eff.org/docs/using.html#pre-and-post-validation-hooks
#      - $PWD/auth.sh:/auth:ro
      # cleanup hook; https://certbot.eff.org/docs/using.html#pre-and-post-validation-hooks
#      - $PWD/cleanup.sh:/cleanup:ro
# Test entrypoint for debugging
   # entrypoint: /test-entrypoint
    environment:
      EMAIL: ops@example.com
    command: ssltest.lent.ink another.lent.ink
volumes:
  shared-challenge-volume: {}

