version: '3'
services:
  cdn:
    image: nginx:alpine
    volumes:
      - cdn:/usr/share/nginx/html:ro
    ports:
      - "80:80"
  ssl:
    image: svlentink/letsencrypt
    volumes:
      - cdn:/tmp/challenge
# Example options:
      # This will enable you to get the actual files, instead of JSON
#      - $PWD/something:/etc/letsencrypt
      # auth-hook; https://certbot.eff.org/docs/using.html#pre-and-post-validation-hooks
#      - $PWD/auth.sh:/auth:ro
      # cleanup hook; https://certbot.eff.org/docs/using.html#pre-and-post-validation-hooks
#      - $PWD/cleanup.sh:/cleanup:ro
# Test entrypoint for debugging
   # entrypoint: /test-entryp
    environment:
      EMAIL: ops@example.com
      COMMONNAME: lent.ink
    command: ssltest.lent.ink another.lent.ink
volumes:
  cdn: {}
