version: '2'
services:
  db:
    extends:
      file: db.yml
      service: db
  tron:
    build: .
    depends_on:
      - db
    env_file:
      - installatron.env
    ports:
      - "${exposed_to_host_port}:443"
    links:
      - db
