version: '2'
services:
  elastic:
    image: sebp/elk
    ports:
      - "80:5601"
    environment:
      - ES_JAVA_OPTS=-Xmx2g -Xms2g
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
