version: '2'
# run this file:
# docker-compose up -f s3-snap.yml
services:
  s3:
    extends:
      file: $PWD/docker-compose.yml
      service: elk
# https://www.elastic.co/guide/en/elasticsearch/plugins/5.1/repository-s3.html
# https://github.com/spujadas/elk-docker/blob/master/Dockerfile#L168
    command: /usr/share/elasticsearch/bin/elasticsearch-plugin install repository-s3 && /usr/local/bin/start.sh
