version: '2'
services:
  firewall:
    image: svlentink/ipfilter
    links:
      - someapp
      - someapp:dontchangethisalias #creating a reference that we'll use
    volumes:
      - $PWD:/passdir:ro #used to get the .htpasswd, don't mount this dir if you do not want it
    ports:
      - 8888:4321 # edit only the first part to specify the port for the host
    environment:
      ALLOWED_IPS: 8.8.8.8/32 85.144.250.1/22
      APP_PORT: 8080 # The port the app wants exposed
  pwd:
    image: m31271n/htpasswd
    volumes:
      - $PWD:/outputdir
    entrypoint: ["htpasswd","-bc","/outputdir/.htpasswd"]
    command: ["myUSERname","myPASSphrase"]

  someapp: #specify here your app, but don't use the ports option (or expose)
    image: svlentink/polymer-example
